### ISSUE TITLE
unable to login into app

### ISSUE THREAD

**Issue by moiz212** [invoiceninja/flutter-client#146]
Hello,
When I set demo to true but getting and exception error please take a look at photo, and also what to add in API_SERECT.??
because when I set demo mode to false I am getting invalid secret error
<img width="518" alt="Screenshot 2020-08-28 at 3 12 13 PM" src="https://user-images.githubusercontent.com/51788555/91546976-e6f1b380-e940-11ea-9cf3-879c88d05d21.png">

**Comment by moiz212** [comment]
and also can you explain what is hosted and self hosted.?
priority goes first to above error

**Comment by hillelcoren** [comment]
I've update the mock data which should fix this. If you use the demo mode you shouldn't need to set a secret value. 

Our app is similar to WordPress. You can either create a hosted account on https://invoiceninja.com or selfhost the app on your own server.

**Comment by moiz212** [comment]
much appreciate your response thank you so much

**Comment by moiz212** [comment]
one more thing when I am using demo mode how can I login into app

**Comment by moiz212** [comment]
actually the issue isn't solve I am still getting the same error

**Comment by hillelcoren** [comment]
Are you building the Flutter app using the latest code on the develop branch of invoiceninja/flutter-client

**Comment by moiz212** [comment]
No, I'm using latest master branch code

**Comment by hillelcoren** [comment]
Ok, please try again with the latest code. I think initially only checked it into the develop branch.
